# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='votes',
        ),
        migrations.AddField(
            model_name='accounts',
            name='currency',
            field=models.CharField(choices=[('EURO', 'EUR'), ('US Dollar', 'USD')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='transfers',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.UUIDField(default=b'DF20766C', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='reserved',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
