# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20181018_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='transfers',
            options={'verbose_name_plural': 'Transfers'},
        ),
        migrations.AlterField(
            model_name='accounts',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EURO'), ('USD', 'US Dollar')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.CharField(default=b'3FA38F9D', editable=False, max_length=128, primary_key=True, serialize=False),
        ),
    ]
