# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20181018_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.CharField(default=b'665AABDA', editable=False, max_length=128, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('country', models.CharField(default='USA', max_length=100)),
                ('mcc', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Merchants',
            },
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='transactions',
            name='transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Transfers'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Accounts'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.CharField(default=b'C439DC12', editable=False, max_length=128, primary_key=True, serialize=False),
        ),
    ]
