# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20181019_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transfers',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.CharField(default=b'1D9E357D', editable=False, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='merchants',
            name='id',
            field=models.CharField(default=b'7A519C3D', editable=False, max_length=128, primary_key=True, serialize=False),
        ),
    ]
