# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20181019_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.CharField(default=b'EEEF2D40', editable=False, max_length=128, primary_key=True, serialize=False)),
                ('description', models.CharField(default='None', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.DeleteModel(
            name='Merchants',
        ),
        migrations.RenameField(
            model_name='transfers',
            old_name='receiver',
            new_name='payee',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='amount',
        ),
        migrations.AddField(
            model_name='transactions',
            name='description',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='transactions',
            name='trtype',
            field=models.CharField(choices=[('CDT', 'Credit'), ('DBT', 'Debit')], default='DBT', max_length=3),
        ),
        migrations.AddField(
            model_name='transfers',
            name='authorized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transfers',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EURO'), ('USD', 'US Dollar')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='transfers',
            name='trtype',
            field=models.CharField(choices=[('CDT', 'Credit'), ('DBT', 'Debit')], default='DBT', max_length=3),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.CharField(default=b'122FF87F', editable=False, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='activities',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Accounts'),
        ),
    ]
