# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20181021_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.CharField(default=b'17D84576', editable=False, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='id',
            field=models.CharField(default=b'BA7D8D90', editable=False, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
