# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20181021_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='presented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfers',
            name='txid',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.CharField(default=b'9CE7FF87', editable=False, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='id',
            field=models.CharField(default=b'2E87B99F', editable=False, max_length=128, primary_key=True, serialize=False),
        ),
    ]
